% This test file was generated by Copilot. Validate the generated output before use.
classdef detectAnomaliesFuncTest < matlab.unittest.TestCase
    properties
        prj
    end

    methods (TestMethodSetup)
        function openProject(testCase)
            try
                testCase.prj = currentProject;
                cd(testCase.prj.RootFolder)
            catch
                open("..\AutoEncoderAnomalyDetection.prj");
                testCase.prj = currentProject;
                cd(testCase.prj.RootFolder)
            end
        end
    end
    
    methods(Test)
        function testDetectAnomaliesWithNoAnomalies(testCase)
            % Test with normal data points
            
            data = load("autoencoder_data.mat","normaldata");
            for i = 1:length(data.normaldata)
                anomalyidx(i) = detectAnomalies(data.normaldata(i));
            end
            
            testCase.verifyEmpty(find(~isnan(anomalyidx)), 'Anomalies should not be detected in normal data.');
        end
        
        function testDetectAnomaliesWithAnomalies(testCase)
            % Test with a known anomaly
            data = load("autoencoder_data.mat","faultydata");
            for i = 1:length(data.faultydata)
                anomalyidx(i) = detectAnomalies(data.faultydata(i));
            end
            
            testCase.verifyNotEmpty(find(~isnan(anomalyidx)), 'There should be anomalies in this test set');
        end
    end
end